package com.owo.dao;

import com.owo.entity.PemesananStatus;
import com.owo.entity.Refund;
import com.owo.utils.DBHelper;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class RefundDAO {

    /**
     * Persists a refund, including where the money should go.
     *
     * <p>The id is generated by the caller in Java. It used to arrive from the JavaScript
     * payload, so a repeated value surfaced a raw {@code SQLITE_CONSTRAINT} string in the UI.
     */
    public static Refund createRefund(Refund refund) throws SQLException {
        String sql = "INSERT INTO refund (id, pemesanan_id, alasan, status, jumlah_refund, "
                + "nama_penerima, rekening_tujuan, status_sebelumnya) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, refund.getId());
            pstmt.setInt(2, refund.getPemesananID());
            pstmt.setString(3, refund.getAlasan());
            pstmt.setString(4, refund.getStatus().name());
            pstmt.setDouble(5, refund.getJumlahRefund());
            pstmt.setString(6, refund.getNamaPenerima());
            pstmt.setString(7, refund.getRekeningTujuan());
            pstmt.setString(8, refund.getStatusSebelumnya() == null
                    ? null : refund.getStatusSebelumnya().dbValue());

            if (pstmt.executeUpdate() == 0) {
                throw new SQLException("Creating refund failed, no rows affected.");
            }
            return refund;
        }
    }

    public static Refund getRefundById(String id) throws SQLException {
        String sql = "SELECT * FROM refund WHERE id = ?";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return mapRefund(rs, id, rs.getInt("pemesanan_id"));
                }
            }
        }
        return null;
    }

    public static List<Refund> getRefundByPemesananId(int pemesananID) throws SQLException {
        String sql = "SELECT * FROM refund WHERE pemesanan_id = ?";
        List<Refund> refundList = new ArrayList<>();

        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, pemesananID);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    refundList.add(mapRefund(rs, rs.getString("id"), pemesananID));
                }
            }
        }
        return refundList;
    }

    private static Refund mapRefund(ResultSet rs, String id, int pemesananID) throws SQLException {
        String alasan = rs.getString("alasan");
        double jumlahRefund = rs.getDouble("jumlah_refund");

        Refund refund = new Refund(id, pemesananID, alasan, jumlahRefund);

        // The column is plain TEXT with no CHECK constraint, so one unexpected value used
        // to throw IllegalArgumentException out of the middle of the list query.
        try {
            refund.setStatus(Refund.RefundStatus.fromDb(rs.getString("status")));
        } catch (IllegalArgumentException e) {
            throw new SQLException("Refund " + id + " has an invalid status", e);
        }

        String statusSebelumnya = rs.getString("status_sebelumnya");
        if (statusSebelumnya != null && !statusSebelumnya.isBlank()) {
            try {
                refund.setStatusSebelumnya(PemesananStatus.fromDb(statusSebelumnya));
            } catch (IllegalArgumentException e) {
                throw new SQLException("Refund " + id + " has an invalid previous status", e);
            }
        }

        refund.setDetailPencairan(rs.getString("nama_penerima"), rs.getString("rekening_tujuan"));
        return refund;
    }

    public static void updateStatus(String id, Refund.RefundStatus status) throws SQLException {
        String sql = "UPDATE refund SET status = ? WHERE id = ?";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, status.name());
            pstmt.setString(2, id);
            if (pstmt.executeUpdate() == 0) {
                throw new SQLException("No refund with id " + id);
            }
        }
    }

    /**
     * @param rekeningTujuan a bank account reference, or a masked card number's last four
     *     digits — never a full PAN, and never a CVV
     */
    public static void updateDetailPencairan(String id, String namaPenerima, String rekeningTujuan)
            throws SQLException {
        String sql = "UPDATE refund SET nama_penerima = ?, rekening_tujuan = ? WHERE id = ?";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, namaPenerima);
            pstmt.setString(2, rekeningTujuan);
            pstmt.setString(3, id);
            if (pstmt.executeUpdate() == 0) {
                throw new SQLException("No refund with id " + id);
            }
        }
    }
}
