package com.owo.dao;

import com.owo.entity.PemesananStatus;
import com.owo.entity.Refund;
import com.owo.utils.DBHelper;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class RefundDAO {

    /**
     * Persists a refund, including where the money should go.
     *
     * <p>The id is generated by the caller in Java. It used to arrive from the JavaScript
     * payload, so a repeated value surfaced a raw {@code SQLITE_CONSTRAINT} string in the UI.
     */
    public static Refund createRefund(Refund refund) throws SQLException {
        String sql = "INSERT INTO refund (id, pemesanan_id, alasan, status, jumlah_refund, "
                + "nama_penerima, rekening_tujuan, status_sebelumnya) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, refund.getId());
            pstmt.setInt(2, refund.getPemesananID());
            pstmt.setString(3, refund.getAlasan());
            pstmt.setString(4, refund.getStatus().name());
            pstmt.setDouble(5, refund.getJumlahRefund());
            pstmt.setString(6, refund.getNamaPenerima());
            pstmt.setString(7, refund.getRekeningTujuan());
            pstmt.setString(8, refund.getStatusSebelumnya() == null
                    ? null : refund.getStatusSebelumnya().dbValue());

            if (pstmt.executeUpdate() == 0) {
                throw new SQLException("Creating refund failed, no rows affected.");
            }
            return refund;
        }
    }

    public static Refund getRefundById(String id) throws SQLException {
        String sql = "SELECT * FROM refund WHERE id = ?";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, id);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    return mapRefund(rs, id, rs.getInt("pemesanan_id"));
                }
            }
        }
        return null;
    }

    public static List<Refund> getRefundByPemesananId(int pemesananID) throws SQLException {
        String sql = "SELECT * FROM refund WHERE pemesanan_id = ?";
        List<Refund> refundList = new ArrayList<>();

        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, pemesananID);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    refundList.add(mapRefund(rs, rs.getString("id"), pemesananID));
                }
            }
        }
        return refundList;
    }

    /**
     * Every refund filed against a booking the customer owns, newest bookings last.
     *
     * <p>Scoped by joining {@code pemesanan}, so ownership is decided by the query rather
     * than by filtering rows the caller was never entitled to read.
     */
    public static List<Refund> getRefundsByCustomerId(int customerId) throws SQLException {
        String sql = "SELECT r.* FROM refund r "
                + "JOIN pemesanan p ON r.pemesanan_id = p.id "
                + "WHERE p.customer_id = ? "
                + "ORDER BY r.pemesanan_id ASC";
        List<Refund> refundList = new ArrayList<>();

        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, customerId);
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    refundList.add(mapRefund(rs, rs.getString("id"), rs.getInt("pemesanan_id")));
                }
            }
        }
        return refundList;
    }

    /** The review queue: every refund currently in one status. */
    public static List<Refund> getRefundsByStatus(Refund.RefundStatus status) throws SQLException {
        String sql = "SELECT * FROM refund WHERE status = ? ORDER BY pemesanan_id ASC";
        List<Refund> refundList = new ArrayList<>();

        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, status.name());
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    refundList.add(mapRefund(rs, rs.getString("id"), rs.getInt("pemesanan_id")));
                }
            }
        }
        return refundList;
    }

    private static Refund mapRefund(ResultSet rs, String id, int pemesananID) throws SQLException {
        String alasan = rs.getString("alasan");
        double jumlahRefund = rs.getDouble("jumlah_refund");

        Refund refund = new Refund(id, pemesananID, alasan, jumlahRefund);

        // The column is plain TEXT with no CHECK constraint, so one unexpected value used
        // to throw IllegalArgumentException out of the middle of the list query.
        try {
            refund.setStatus(Refund.RefundStatus.fromDb(rs.getString("status")));
        } catch (IllegalArgumentException e) {
            throw new SQLException("Refund " + id + " has an invalid status", e);
        }

        String statusSebelumnya = rs.getString("status_sebelumnya");
        if (statusSebelumnya != null && !statusSebelumnya.isBlank()) {
            try {
                refund.setStatusSebelumnya(PemesananStatus.fromDb(statusSebelumnya));
            } catch (IllegalArgumentException e) {
                throw new SQLException("Refund " + id + " has an invalid previous status", e);
            }
        }

        refund.setDetailPencairan(rs.getString("nama_penerima"), rs.getString("rekening_tujuan"));

        int reviewer = rs.getInt("direview_oleh");
        refund.setReview(rs.wasNull() ? null : reviewer,
                com.owo.utils.SqlDates.parseNullableDateTime(
                        rs.getString("waktu_review"), "waktu_review"));
        return refund;
    }

    /**
     * Records a refund decision and its effect on the booking as one transaction.
     *
     * <p>These used to be three writes on three connections. A failure after the first
     * left the refund decided while the booking stayed at {@code REFUND_IN_PROGRESS}, and
     * because deciding requires {@code PENDING_REVIEW} nothing could ever decide it again
     * — the refund was wedged permanently with no retry path.
     *
     * <p>The refund update is conditional on the status it was read at, so two
     * administrators deciding at once cannot both succeed.
     *
     * <p>The reviewer and the moment of the decision are written in the same statement as
     * the status, so a decided refund can never exist without a record of who decided it.
     *
     * @param releaseTiketId ticket to return to the catalogue, or null to leave it claimed
     * @param reviewerId the administrator making the decision
     * @return false if the refund was no longer awaiting review
     */
    public static boolean applyDecision(String refundId, Refund.RefundStatus from,
            Refund.RefundStatus to, int pemesananId, PemesananStatus bookingStatus,
            Integer releaseTiketId, int reviewerId, java.time.LocalDateTime waktuReview)
            throws SQLException {

        String decideSql = "UPDATE refund SET status = ?, direview_oleh = ?, waktu_review = ? "
                + "WHERE id = ? AND status = ?";
        String bookingSql = "UPDATE pemesanan SET status = ? WHERE id = ?";
        String releaseSql = "UPDATE tiket SET tersedia = 1 WHERE id = ?";

        try (Connection conn = DBHelper.getConnection()) {
            conn.setAutoCommit(false);
            try {
                try (PreparedStatement decide = conn.prepareStatement(decideSql)) {
                    decide.setString(1, to.name());
                    decide.setInt(2, reviewerId);
                    decide.setString(3, com.owo.utils.SqlDates.format(waktuReview));
                    decide.setString(4, refundId);
                    decide.setString(5, from.name());
                    if (decide.executeUpdate() == 0) {
                        conn.rollback();
                        return false;
                    }
                }

                try (PreparedStatement booking = conn.prepareStatement(bookingSql)) {
                    booking.setString(1, bookingStatus.dbValue());
                    booking.setInt(2, pemesananId);
                    if (booking.executeUpdate() == 0) {
                        throw new SQLException("No pemesanan with id " + pemesananId);
                    }
                }

                if (releaseTiketId != null) {
                    try (PreparedStatement release = conn.prepareStatement(releaseSql)) {
                        release.setInt(1, releaseTiketId);
                        release.executeUpdate();
                    }
                }

                conn.commit();
                return true;
            } catch (SQLException e) {
                conn.rollback();
                throw e;
            }
        }
    }

    /**
     * Moves a refund from one status to another, only if it is still in {@code from}.
     *
     * <p>Reading the status and then writing unconditionally lets two administrators
     * working the same disbursement queue both succeed, so a refund marked completed by
     * one is marked failed by the other. Putting the expected status in the {@code WHERE}
     * makes the loser's update match nothing, the same way the booking claim tests
     * availability in its own update.
     *
     * @return false if no row matched — the refund is gone, or no longer in {@code from}
     */
    public static boolean advanceStatus(String id, Refund.RefundStatus from,
            Refund.RefundStatus to) throws SQLException {
        String sql = "UPDATE refund SET status = ? WHERE id = ? AND status = ?";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, to.name());
            pstmt.setString(2, id);
            pstmt.setString(3, from.name());
            return pstmt.executeUpdate() > 0;
        }
    }

    /** Every refund in any of {@code statuses}, oldest booking first. */
    public static List<Refund> getRefundsByStatus(java.util.Collection<Refund.RefundStatus> statuses)
            throws SQLException {
        List<Refund> refundList = new ArrayList<>();
        if (statuses == null || statuses.isEmpty()) {
            return refundList;
        }

        // Placeholders are generated from the collection's size, never from its contents.
        String placeholders = String.join(",", java.util.Collections.nCopies(statuses.size(), "?"));
        String sql = "SELECT * FROM refund WHERE status IN (" + placeholders
                + ") ORDER BY pemesanan_id ASC";

        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            int index = 1;
            for (Refund.RefundStatus status : statuses) {
                pstmt.setString(index++, status.name());
            }
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    refundList.add(mapRefund(rs, rs.getString("id"), rs.getInt("pemesanan_id")));
                }
            }
        }
        return refundList;
    }

    public static void updateStatus(String id, Refund.RefundStatus status) throws SQLException {
        String sql = "UPDATE refund SET status = ? WHERE id = ?";
        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, status.name());
            pstmt.setString(2, id);
            if (pstmt.executeUpdate() == 0) {
                throw new SQLException("No refund with id " + id);
            }
        }
    }

    /**
     * @param rekeningTujuan a bank account reference, or a masked card number's last four
     *     digits — never a full PAN, and never a CVV
     */
    public static void updateDetailPencairan(String id, String namaPenerima, String rekeningTujuan)
            throws SQLException {
        if (!updateDetailPencairan(id, namaPenerima, rekeningTujuan, null)) {
            throw new SQLException("No refund with id " + id);
        }
    }

    /**
     * Rewrites the payee, optionally only while the refund is still in {@code onlyWhen}.
     *
     * <p>Checking the status in the caller and then updating unconditionally leaves a
     * window in which an approval lands between the two, writing a new payee onto a refund
     * that has already been signed off. Making the status part of the {@code WHERE} closes
     * it, the same way the booking claim tests availability in its own update.
     *
     * @return false if no row matched — the refund is gone, or no longer in that status
     */
    public static boolean updateDetailPencairan(String id, String namaPenerima,
            String rekeningTujuan, Refund.RefundStatus onlyWhen) throws SQLException {
        String sql = "UPDATE refund SET nama_penerima = ?, rekening_tujuan = ? WHERE id = ?"
                + (onlyWhen == null ? "" : " AND status = ?");

        try (Connection conn = DBHelper.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setString(1, namaPenerima);
            pstmt.setString(2, rekeningTujuan);
            pstmt.setString(3, id);
            if (onlyWhen != null) {
                pstmt.setString(4, onlyWhen.name());
            }
            return pstmt.executeUpdate() > 0;
        }
    }
}
